### ISSUE TITLE
Library issue

### ISSUE THREAD

**Issue by faultydevil23** [techinessoverloaded/progress-dialog#1]
Iam facing an issue with your library when iam cloning it its showing me an error and that is "Library not found in saved repositories" hope u will solve this ASAP...
Thank you !

**Comment by techinessoverloaded** [comment]
> Iam facing an issue with your library when iam cloning it its showing me an error and that is "Library not found in saved repositories" hope u will solve this ASAP...
> Thank you !

Hi ! Sorry for the late reply ! Has the issue been resolved now ? If not, can you elaborate on the issue (with screenshots maybe) ?
