### ISSUE TITLE
[FEATURE REQUEST] Add Timer Increasing Mod

### ISSUE THREAD

**Issue by vzool** [techinessoverloaded/progress-dialog#13]
**Is your feature request related to a problem? Please describe.**
Yes, I think so. This will solve how much time the process is taken if a user complains.

**Describe the solution you'd like**
Add a new mod for a timer that increases and updates the UI every second, so the UI is just a text like this `00:00:00`

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by techinessoverloaded** [comment]
Hi, Thanks for suggesting a Feature. You're saying that an option should be given to display the time elapsed in the progressdialog right ? Have I understood in the right manner ?

**Comment by techinessoverloaded** [comment]
> Yes, indeed.

Okay ! I guess the feature should be exposed for MODE_DETERMINATE Mode of ProgressDialog alone. I will implement the feature and release it in the next version.

**Comment by techinessoverloaded** [comment]
Hi, I have added this feature in version 1.5.1.
