### ISSUE TITLE
Cancel button is always shown.

### ISSUE THREAD

**Issue by mg2000** [techinessoverloaded/progress-dialog#3]
I programmed like below.

`val progressDialog = ProgressDialog(requireContext())`
`progressDialog.show()`

But 'Cancel' button is shown. I don't know why.

**Comment by ArleyPereira** [comment]
progressDialog.hideNegativeButton()

**Comment by techinessoverloaded** [comment]
Yeah, you can use hideNegativeButton() method for now. My schedule is tight and I am unable to check the code for the pointed out issue. Will sort out the issue ASAP. Till then, use hideNegativeButton() method.

**Comment by techinessoverloaded** [comment]
> I programmed like below.
> 
> `val progressDialog = ProgressDialog(requireContext())` `progressDialog.show()`
> 
> But 'Cancel' button is shown. I don't know why.

Thanks for pointing out this issue. I have resolved this issue in version 1.3.1. Kindly use version 1.3.1 to see the changes.
